#!/usr/bin/env ruby

Dir.glob('???-*.md').sort.each do |file|
  content = File.read(file)

  title = content.match(/^# (.+)$/)[1]
  _, site, url, date = *content.match(/^_Published on \[(.+)\]\((.+)\) on (.+)_$/)

  puts "* [#{title}](#{url})"
end
